# Generated by Django 2.1.4 on 2018-12-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(max_length=400)),
                ('article_id', models.CharField(max_length=36)),
                ('author_id', models.IntegerField(default=1)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
